language: nix

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

env:
  - EMACS_CI=emacs-25-3

script:
  - emacs --version
  - make ci-dependencies
  - make check
